# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(38,42,54);    \n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.distance = QtWidgets.QSlider(self.frame)
        self.distance.setGeometry(QtCore.QRect(60, 660, 160, 22))
        self.distance.setMaximum(5)
        self.distance.setSingleStep(1)
        self.distance.setProperty("value", 1)
        self.distance.setOrientation(QtCore.Qt.Horizontal)
        self.distance.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.distance.setObjectName("distance")
        self.camera = QtWidgets.QPushButton(self.frame)
        self.camera.setGeometry(QtCore.QRect(1150, 20, 75, 23))
        self.camera.setObjectName("camera")
        self.cameraStream = QtWidgets.QLabel(self.frame)
        self.cameraStream.setGeometry(QtCore.QRect(310, 50, 640, 480))
        self.cameraStream.setText("")
        self.cameraStream.setObjectName("cameraStream")
        self.distance_value = QtWidgets.QLabel(self.frame)
        self.distance_value.setGeometry(QtCore.QRect(120, 630, 47, 13))
        self.distance_value.setObjectName("distance_value")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 20, 131, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(940, 590, 101, 20))
        self.label_2.setObjectName("label_2")
        self.people = QtWidgets.QLabel(self.frame)
        self.people.setGeometry(QtCore.QRect(970, 620, 47, 13))
        self.people.setObjectName("people")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(1070, 20, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera.setText(_translate("MainWindow", "start camera"))
        self.distance_value.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Social Detection</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Number of people"))
        self.people.setText(_translate("MainWindow", "0"))
        self.radioButton.setText(_translate("MainWindow", "depth frame"))
